# Plugins
plugins:
  - jekyll-sitemap

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Healthcare AI Symposium 2026"
email: "Health_AI@a-star.edu.sg"
description: "Healthcare AI Symposium 2026, 8-10 July 2026, Singapore"
baseurl: ""
url: "https://hai-webpage.github.io"
#googleAnalyticsTrackingId: "G-01Y9DZ782N"
#googleAnalyticsSiteUrl: "hai-webpage.github.io"
#siteVerification: ""

# Organizer Info
organizerName: "A*STAR IHPC"
organizerAlternateName: "Institute of High Performance Computing, A*STAR"
organizerDescription: "Leadership in computational modelling, simulation and AI to solve major scientific, industrial and societal challenges."
organizerEmail: "Health_AI@a-star.edu.sg"
organizerLogo: "/img/seo/ASTAR_IHPC_Horizontal_Logo_RGB.png"
organizerLink: "http://www.a-star.edu.sg/ihpc"

# Head
metaKeywords: "event, hai, healthcare, ai, singapore, medtech, digital, innovation"

# Documents
c4sponsorsUrl: "/sponsor/"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/programme/", text: "Programme"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/poster/", text: "Posters"}
 - {permalink: "/pitch/", text: "Pitch"}
 - {permalink: "/sponsor/", text: "Sponsor"}
 - {link: "https://www.healthsymposium.ai/", text: "HAI 2025"}
bottomNavigationLinks:
 - {permalink: "/sponsor/", text: "Become a sponsor"}
rightNavigationButtons:
 - {permalink: "/sponsor/", text: "Become a sponsor"}

# Hero Block
heroImage: "HAI26 Website Masthead.png"
heroTitle: "3rd Annual<br>Healthcare AI Symposium<br>2026"
eventDate: "Singapore, 8-10 July 2026"
heroButtons:
 - {link: "https://a-star-engagementportal.glueup.com/event/162425/register/", text: "Register Now"}

# About Block
aboutTitle: "About HAI 2026"
aboutDescription: "The 3rd edition of the Healthcare AI (HAI) Symposium returns to Singapore from 8–10 July 2026, convening the healthcare innovation ecosystem to exchange ideas, forge collaborations, and connect across disciplines. <br><br>This year’s symposium is dedicated to “<b>Designing the Future of Intelligent Health: Advancing Healthcare Through AI, MedTech and Digital Systems</b>.” <br><br><br>Join us to explore the latest developments in AI, MedTech, and digital healthcare, alongside policymakers, healthcare professionals, academics, investors, and industry leaders, as we shape the future of intelligent health together."
aboutBlock:
 - {title: "Experience", image: "experience.png", text: "two-days of cutting-edge insights in healthcare AI and digital innovations." }
 - {title: "Gain", image: "gain.png", text: "practical skills in our full-day hands-on workshop." }
 - {title: "Showcase", image: "showcase.png", text: "your startup at the Healthcare Innovation Pitch Challenge!" }

# Statistic Block
statisticTitle: "HAI 2026 Highlights"
statisticBlockImage: "highlights.png"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from Singapore and abroad"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "including clinicians, technologists and investors"}
 - {count: "15", specialCharacter: "+", info: "tech booths", detail: "showcasing healthcare innovations"}
 - {count: "6", specialCharacter: "", info: "frontier themes", detail: "from Foundation Models in Healthcare to Investing in the Future of Health AI"}

# Partners Block
organizersTitle: "Organisers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Footer
socialLinks:
 - {link: "https://www.linkedin.com/company/healthcare-ai-symposium/", icon: "linkedin"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
  # - {link: "https://www.a-star.edu.sg/ihpc", text: "Institute of High Performance Computing (A*STAR IHPC)"}
   - {link: "https://www.a-star.edu.sg", text: "Agency for Science, Technology and Research (A*STAR)"}
 -
  title: "Contact"
  links:
   - {link: "mailto:Health_AI@a-star.edu.sg", text: "Health_AI@a-star.edu.sg"}

# Speakers List Block
showSessions: true

# # Team Block
# teamBlockTitle: "About us"
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."


# Poster
posterTitle: "HAI 2026 Call for Posters"
posterTheme: "Designing the Future of Intelligent Health: Advancing Healthcare Through AI, MedTech, and Digital Systems"
posterUrl: "https://form.gov.sg/6925656607d8882d42f05581"
posterButtonText: "Register your poster"
posterHeroImage: "HAI25 background.jpg"

# Poster About Block
posterDescription: "The Healthcare AI Symposium 2026 invites undergraduate, postgraduate, and doctoral students to submit posters presenting their translational research aligned with the theme<br><br>“<b>Designing the Future of Intelligent Health: Advancing Healthcare Through AI, MedTech, and Digital Systems</b>”.<br><br>This is an opportunity to share their research work and engage with researchers, clinicians, and industry leaders."
posterTopicsTitle: "Invited Topics"
posterTopicsRows:
 - {title: "AI-driven Diagnostics, Monitoring and Triage", image: "diagnostics.png"}
 - {title: "Agentic AI for Healthcare", image: "agentic.png"}
 - {title: "Digital Health, Clinical Informatics, and Medical Data Science", image: "digitalhealth.png"}
 - {title: "Medical Image Analysis and Computer Vision", image: "medicalimage.png"}
 - {title: "MedTech and Medical Devices", image: "medtech.png"}
 - {title: "Multimodal Learning and Foundation Models", image: "foundationmodel.png"}
 - {title: "Safety, Fairness, and Evaluation of Clinical AI Systems", image: "safety.png"}
 - {title: "Signal Processing and Physiological Measurements", image: "signalprocessing.png"}

# Poster Important Dates
posterDatesTitle: "Important Dates"
posterDatesRows:
 - {title: "Abstract Submission Deadline", date: "Tuesday, 31 March 2026"}
 - {title: "Notification of Acceptance", date: "Friday, 29 May 2026"}
 - {title: "Registration Deadline", date: "Monday, 15 June 2026"}
 - {title: "Poster Session", date: "Wednesday, 8 July 2026 & Thursday, 9 July 2026"}

# Poster FAQ Block
posterFaqRows:
 - {title: "Eligibility", details: "Students from all backgrounds (engineering, computer science, biomedical sciences, public health, medicine, and related fields) are encouraged to submit. Collaborative or interdisciplinary work is welcomed."}
 - {title: "Submission Guidelines", details: "Please submit a 1 page sumamary using the IEEE conference template: https://www.ieee.org/conferences/publishing/templates"}
 - {title: "Evaluation", details: "Submissions will be evaluated based on scholarly merit, clarity, innovation, methodological rigor, and potential impact in healthcare applications. Accepted posters will be presented during the dedicated poster session."}
 - {title: "Important dates", details: "Submission deadline: TBD; Notification of acceptance: TBD; Poster session: 8-9 July 2026"}


# Pitch Challenge
pitchTitle: "<b>Healthcare Innovation Pitch Challenge</b> 2026"
pitchTheme: "Care Deliveries Transformation - How Technology is Redefining Healthcare"
pitchUrl: "https://forms.cloud.microsoft/r/YHbPGCB49U"
pitchButtonText: "Apply to pitch"
pitchHeroImage: "HAI25 background.jpg"

# Pitch About Block
pitchBenefitCards:
 - {title: "Connect", image: "connect.png", information: 'with leading investors and industry experts'}
 - {title: "Network", image: "network.png", information: 'with potential partners and mentors'}
 - {title: "Elevate", image: "elevate.png", information: 'your visibility within the healthcare AI community'}

# Pitch Challenge Important Dates
pitchDatesTitle: "Important Dates"
pitchDatesRows:
 - {title: "Application Deadline", date: "Tuesday, 31 March 2026"}
 - {title: "Notification of Acceptance", date: "Sunday, 31 May 2026"}
 - {title: "Pitch Date", date: "Thursday, 9 July 2026"}

# Pitch Challenge Why Apply Block
whyApplyTitle: "Why apply"
whyApplyDescription: "Participants will have the opportunity to pitch their ideas and receive expert feedback from a penal of judges and industry leaders.<br><br>The top three teams will gain access to:<br>- Recognition during the symposium<br>- Exclusive networking opportunities with investors and strategic partners<br>- Potential follow-up discussions or funding introductions"

# Pitch Important Notes
pitchNotesTitle: "Important Notes"
pitchNotesRows:
 - {title: "Attractive cash prizes for the top 3 teams", image: "cashprizes.png"}
 - {title: "Global healthcare companies and startups are welcome to apply", image: "companiesstartups.png"}
 - {title: "Shortlisted teams will present onsite at the sysmposium", image: "presentonsite.png"}

# Pitch Challenge FAQ Block
pitchFaqRows:
 - {title: "Who should apply?", details: "Startups or companies working on innovative healthcare or AI-driven sotluions are welcome to apply. We accept early-stage, growth-stage, and research-based ventures."}
 - {title: "Is there a fee to participate?", details: "No, participation in the pitch challenge is free of charge. However, teams are responsible for their own travel and accommodation if attending the event."}
 - {title: "How do I register, and what is required in the application?", details: "All applicants must register by completing the online registration form and submit the following:<br>- A pitch deck (PDF or PowerPoint, max file size of 100Mb)<br>- A pitch video (Length: up to 3.5 minutes, format and size: .mp4, .avi, max file size of 1 GB)"}
 - {title: "How long is the pitch?", details: "Each team will have 4 minutes to pitch, followed by 2-3 minutes of Q&A with the judges."}
 - {title: "When is the application deadline?", details: "The deadline for submission is "}
 - {title: "What is the judging criteria?", details: "Judges will evaluate the pitches based on <br>- Innovation and uniqueness<br>- Impact on healthcare<br>- Feasibility and scalability<br>- Team Capability<br>- Clarity of presentation"}
 - {title: "What are the benefits of participating in the Healthcare Innovation Pitch Challenge?", details: "Opportunity to pitch and receive professional feedback from the judging panel and industry experts. Top 3 teams will receive:<br>- Recognition at the symposium.<br>- Networking opportunities with investors and partners.<br>- Potential follow-up meetings or funding introductions.</li></ul>"}
 - {title: "How many members can attend the symposium?", details: "Up to two members from the same company will receive complimentary access to HAI 2026. Additional members may register to attend the event."}
 - {title: "Can I submit more than one application?", details: "Founders should only submit one application per company."}
 - {title: "Is may application confidential?", details: "Yes, all applications are kept confidential within the organising team and shared only with the judging panel as required for their evaluation."}


# Sponsorship
sponsorDescription: "Be part of shaping the future of healthcare innovation at HAI 2026 - where breakthrough ideas and emerging technologies come together to accelerate real-world healthcare impact."
sponsorRowsTitle: "Why sponsor?"
sponsorRows:
 - {title: "Brand Visibility", image: "brand.png", details: "Amplify your brand with prominent logo placement across event collateral, digital platforms, and on-site signage, reaching industry leaders and decision-makers throughout the event."}
 - {title: "Strategic Networking", image: "networking.png", details: "Gain direct access to C-suite executives, senior decision-makers, leading researchers, and healthcare innovators. Build meaningful connections that support partnerships, catalyse innovation, and drive long-term business growth."}
 - {title: "Speaking Opportunities", image: "speaking.png", details: "Showcase your expertise through curated panel discussions, keynote sessions and presentations, positioning your organisation as a leader in healthcare AI and innovation."}
 - {title: "Innovation Showcase", image: "innovation.png", details: "Secure premium exhibition space to demonstrate your latest solutions and technologies. Engage directly with potential clients, collaborators, and investors in a high-impact setting."}

sponsorEnquiryTitle: "For Sponsorship Enquiries"
sponsorEnquirySubtitle: "Shape the Future of Healthcare AI"
sponsorEnquiryDescription: "Connect with innovators driving healthcare transformation"
sponsorEnquiryButton: "Request sponsorship details"
sponsorEnquiryImage: "highlights.png"